set(ROOT_DIRECTORY "/home/vdev/git/ViennaMesh")
set(CTEST_SOURCE_DIRECTORY $ENV{VIENNAMESHPATH})
set(USED_PROJECTS "VIENNAGRID" "VIENNAMESH")
set(CTEST_BUILD_OPTIONS "-DBUILD_PYVIENNAMESH=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TOOLS=OFF -DVIENNAMESH_WITH_VGMODELER=OFF")

set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(CTEST_BUILD_FLAGS) # build tests sequentially. Not enough RAM for parallel builds.
set(CTEST_COMMAND "${CTEST_EXECUTABLE_NAME} -j2") # run tests in parallel
