set(ROOT_DIRECTORY "D:/git/ViennaMesh")
set(CTEST_SOURCE_DIRECTORY $ENV{VIENNAMESHPATH})
set(USED_PROJECTS "VIENNAGRID" "VIENNAMESH")
set(CTEST_BUILD_OPTIONS "-DBUILD_PYVIENNAMESH=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TOOLS=OFF")
